### ISSUE TITLE
tip for your div issue

### ISSUE THREAD

**Issue by patriciachrysy** [dili021/Design-teardown#1]
Hello guys, actually the problem is this:
div {
    display: grid;
    place-items: center;
}
this selector is centering the items in all the divs of your page. Even in those containing other divs.
Let's try to remove it and use this instead:
.div-text {
    display: grid;
    align-items: center;
    text-align: center;
}
Then add this class only in div tags that contain text, not the wrappers, only those divs who directly contains the "p" tag.
Please get rid of this:
!!!! div {
    display: grid;
    place-items: center;
} !!!!

**Comment by Kyle-Law** [comment]
Agreed to @patriciachrysy . The problem arose because you have **div of div** for that part. `place-items: center;` will shrink its children to the center.

**Comment by Kyle-Law** [comment]
If you don't like removing that and giving all containers individually, setting `place-items: unset` to the class **.guides-grid** could temporarily solve the issue.

**Comment by patriciachrysy** [comment]
@Kyle-Law that's a good alternative too

**Comment by dili021** [comment]
Thanks guys, changing the grid into a section fixed it.
